spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auction
    username: root
    password: root
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  tomcat:
    access-log-enabled: true

javascript:
  url: http://localhost:3000/static/js/bundle.js

